### ISSUE TITLE
:compiler-options in .cljs.edn behavior is a bit unexpected

### ISSUE THREAD

**Issue by piranha** [adzerk/boot-cljs#38] opened 2015-01-18 12:28 UTC
The problem is if I put some compiler options in my cljs task (in `build.boot`), and have few `.cljs.edn` files, and one of them overrides some option, then other `.cljs.edn` files will have this option overriden to new value. I.e. if I have `{:target :nodejs}` for one file, I have to specify `{:target nil}` for another file explicitly. I don't think that was intended.

**Comment by stephanos** [comment] 2015-01-19 14:18
Ah, maybe this explains #36

**Comment by piranha** [comment] 2015-01-19 14:44
Hah, seems like the case. I guess you can try adding `{:target nil}`. :)

**Comment by micha** [comment] 2015-01-19 15:50
I'm marking this as duplicate of #36.

**Closed** 2015-01-19 15:50 UTC
Labels: duplicate
